### ISSUE TITLE
Use New Map - *CRITICAL*

### ISSUE THREAD

**Issue by decause** [DevProgress/lin#3]
![maya-lin-map-102816b](https://cloud.githubusercontent.com/assets/427420/19824352/78d3d1de-9d23-11e6-8fae-107df84209b5.png)

**Comment by kahneraja** [comment]
the size of this map clashes with the layout of the current map. can we get an image that is built in the same dimensions as this one?
https://www.hillaryclinton.com/artist/lin/bg-desktop-wide.jpg
